#!/usr/bin/env python

from pickle import TRUE
import rospy
import actionlib

from navigate_to_pose_pkg.simple_nav_helpers import PurePursuitController
from navigate_to_pose_pkg.simple_nav_helpers import SimpleNavHelpers

from navigate_to_pose_pkg.msg import NavigateToPoseAction
from navigate_to_pose_pkg.msg import NavigateToPoseFeedback
from navigate_to_pose_pkg.msg import NavigateToPoseResult

from geometry_msgs.msg import Twist


class NavigateToPoseServerNode():
    def __init__(self, *args):

        self.feedback = NavigateToPoseFeedback()
        self.result = NavigateToPoseResult()

        self.action_server = actionlib.SimpleActionServer(
            "/navigate_to_pose", NavigateToPoseAction, execute_cb=self.server_callback, auto_start=False)
        self.action_server.start()

        self.cmd_vel_pub = rospy.Publisher("cmd_vel", Twist, queue_size=1)

        self.helpers = SimpleNavHelpers()
        self.controller = PurePursuitController(1.0, 5.0, 0.5, 0.5)

        rospy.loginfo("Started naviagte_to_pose action")

    def server_callback(self, goal):
        rospy.loginfo("Recieved a goal")
        rospy.loginfo(goal.goal_pose)
        dist_to_goal_satisfied = False
        rot_to_goal_satisfied = False

        rate = rospy.Rate(15)

        while not (dist_to_goal_satisfied and rot_to_goal_satisfied) and not rospy.is_shutdown():

            if self.action_server.is_preempt_requested():
                rospy.loginfo("Preempted simple_nav action server")
                self.action_server.set_preempted()
                dist_to_goal_satisfied = True
                rot_to_goal_satisfied = True
                break

            curr_robot_pose = self.helpers.get_curr_robot_pose()
            curr_dist_to_goal = self.helpers.pose_euclidean_dist(
                curr_robot_pose.pose, goal.goal_pose.pose)

            self.feedback.remaining_distance_to_goal = curr_dist_to_goal
            self.action_server.publish_feedback(self.feedback)

            # VERY SIMPLE PURE PURSUIT CONTROLLER
            dist_error, rot_error = self.controller.compute_error(
                curr_robot_pose, goal.goal_pose)

            if dist_error < 0.1:
                rospy.loginfo("We are at goal now, correcting the heading")
                dist_to_goal_satisfied = True

            if dist_to_goal_satisfied and (rot_error < 0.1):
                rospy.loginfo(
                    "Corrected the heading,")
                rot_to_goal_satisfied = True

            if (dist_to_goal_satisfied and rot_to_goal_satisfied):
                self.result.success = True
                self.action_server.set_succeeded()
                rospy.loginfo("Navigation was a success")

            v_in, w_in = self.controller.compute_velocities(
                curr_robot_pose, goal.goal_pose, dist_to_goal_satisfied)

            computed_velocity = Twist()
            computed_velocity.linear.x = v_in
            computed_velocity.angular.z = w_in
            self.cmd_vel_pub.publish(computed_velocity)
            rate.sleep()


def main():
    rospy.init_node("NavigateToPoseServerNode")
    NavigateToPoseServerNode()
    rospy.spin()


if __name__ == '__main__':
    main()
